ALTER TABLE cashier_shifts
  ADD COLUMN ip_address VARCHAR(45) NULL,
  ADD COLUMN user_agent VARCHAR(255) NULL,
  ADD COLUMN created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  ADD COLUMN updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  ADD COLUMN terminal_active_key TINYINT GENERATED ALWAYS AS (CASE WHEN status = 'ACTIVE' THEN 1 ELSE NULL END) STORED,
  ADD UNIQUE KEY uniq_cashier_shifts_terminal_active (terminal_name, terminal_active_key);
